// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTD4hVKygRLY8Nq5Z0IFpUXKRoemjk2I',
    appId: '1:876738271742:web:2753a9dd6b0c1ead4d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    authDomain: 'testapp-4e95c.firebaseapp.com',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    measurementId: 'G-SMD850TWYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvsyezKEmZStWM5AXP1pNAHatA85UlWiM',
    appId: '1:876738271742:android:c31552fc8c62b76d4d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImrdoQkJjoF5GF-XJFdLt_gzzIfD77jQ',
    appId: '1:876738271742:ios:fa5a20f5fe30b4114d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImrdoQkJjoF5GF-XJFdLt_gzzIfD77jQ',
    appId: '1:876738271742:ios:fa5a20f5fe30b4114d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaTD4hVKygRLY8Nq5Z0IFpUXKRoemjk2I',
    appId: '1:876738271742:web:f79e19d149a0af194d88af',
    messagingSenderId: '876738271742',
    projectId: 'testapp-4e95c',
    authDomain: 'testapp-4e95c.firebaseapp.com',
    storageBucket: 'testapp-4e95c.firebasestorage.app',
    measurementId: 'G-WYTRHPMTH8',
  );
}
